apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: postgresql
spec:
  storageClassName: postgresql-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
