apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
  POSTGRES_PASSWORD: ZXhhbXBsZTEyMwo=
# POSTGRES_PASSWORD=example123